### ISSUE TITLE
Loading Titanic Dataset

### ISSUE THREAD

**Issue by impulsecorp** [carefree0910/carefree-data#1]
I want to try use your program on Titanic but am unsure how to split the csv file into x and y. I tried the code below but it did not work:
    train = 'titanic_train.csv'
    label_column = 'Survived'
    data = TabularData().read(train)
    assert data.processed == data.transform(train)
    x, y = data.processed.xy

**Comment by carefree0910** [comment]
For a quick solution, you may try this:

```python
# y=1 means the index of label column is 1
data = TabularData(label_name=label_column).read(train, y=1)
```

**Comment by impulsecorp** [comment]
After processing for a while, it gives this error:

root@server1:~/newautoml# python3 cfl.py
  0%|                                                                                                         | 0/10 [00:00<?, ?it/s]~~~ [warning] '/root/newautoml/__tmp__/b614559f/0/checkpoints' already exists, all of its contents will be removed
  0%|                                                                                                         | 0/10 [05:46<?, ?it/s]
Traceback (most recent call last):
  File "cfl.py", line 24, in <module>
    num_repeat=2, num_parallel=0, num_search=10
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 368, in tune_with
    hpo.search(x, y, estimators, x_cv, y_cv, **search_config)
  File "/usr/local/lib/python3.6/dist-packages/cftool/ml/hpo/base.py", line 149, in search
    self.patterns[self.last_code] = self._core(param, convert=True, parallel_run=num_jobs > 1)
  File "/usr/local/lib/python3.6/dist-packages/cftool/ml/hpo/base.py", line 91, in _core
    patterns = created if self._converter is None else self._converter(created)
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 326, in _converter
    wrappers = list(map(load_task, next(iter(created[0].values()))))
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 188, in load_task
    return next(iter(load(saving_folder=task.saving_folder).values()))
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 460, in load
    wrappers = {k: Wrapper.load(v, compress=True) for k, v in paths.items()}
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 460, in <dictcomp>
    wrappers = {k: Wrapper.load(v, compress=True) for k, v in paths.items()}
  File "/usr/local/lib/python3.6/dist-packages/cflearn/bases.py", line 836, in load
    pipeline.restore_checkpoint(folder)
  File "/usr/local/lib/python3.6/dist-packages/cflearn/bases.py", line 648, in restore_checkpoint
    self.load_state_dict(torch.load(pipeline_file, map_location=self.model.device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Pipeline:
        size mismatch for model.encoders.135.encoders.embedding.embedding.weight: copying a param with shape torch.Size([2, 2]) from checkpoint, the shape in current model is torch.Size([1, 1]).
        size mismatch for model.encoders.1393.encoders.embedding.embedding.weight: copying a param with shape torch.Size([2, 2]) from checkpoint, the shape in current model is torch.Size([1, 1]).
        size mismatch for model.encoders.1394.encoders.embedding.embedding.weight: copying a param with shape torch.Size([2, 2]) from checkpoint, the shape in current model is torch.Size([1, 1]).
        size mismatch for model.encoders.1395.encoders.embedding.embedding.weight: copying a param with shape torch.Size([2, 2]) from checkpoint, the shape in current model is torch.Size([1, 1]).
        size mismatch for model.encoders.1396.encoders.embedding.embedding.weight: copying a param with shape torch.Size([2, 2]) from checkpoint, the shape in current model is torch.Size([1, 1]).
        size mismatch for model.encoders.1398.encoders.embedding.embedding.weight: copying a param with shape torch.Size([2, 2]) from checkpoint, the shape in current model is torch.Size([1, 1]).
        size mismatch for model.encoders.1399.encoders.embedding.embedding.weight: copying a param with shape torch.Size([2, 2]) from checkpoint, the shape in current model is torch.Size([1, 1]).
        size mismatch for model.encoders.1400.encoders.embedding.embedding.weight: copying a param with shape torch.Size([2, 2]) from checkpoint, the shape in current model is torch.Size([1, 1]).
        size mismatch for model.encoders.1401.encoders.embedding.embedding.weight: copying a param with shape torch.Size([2, 2]) from checkpoint, the shape in current model is torch.Size([1, 1]).

**Comment by carefree0910** [comment]
This might happen if you did not clear the previous `__tmp__` so `cflearn` may try to load your previous checkpoints 😉 It reminds me to clear it inside `cflearn`, and I've already added a TODO 😆

For a quick solution, you can `rm -r` the `__tmp__` folder manually 😁

However, using `TabularData` alone will lose some advantages because it can only use `OneHot` encodings. It is highly recommended to use [`carefree-learn`](https://github.com/carefree0910/carefree-learn) alone if you are using it to train neural networks, here's an example:

```python
import cflearn
from cfdata.tabular import *

if __name__ == '__main__':
    train = 'titanic_train.csv'
    hpo = cflearn.tune_with(
        train,
        task_type=TaskTypes.CLASSIFICATION,
        read_config={"y": 1},
        num_parallel=0
    )
    _, patterns = cflearn.repeat_with(train, **hpo.best_param, read_config={"y": 1}, num_jobs=0)
    ensemble = cflearn.EnsemblePattern(patterns)
```

After you get `ensemble`, you can use it to predict (directly) on files:

```python
ensemble.predict(train)
```

It'll be much faster and should achieve a better result 😉

> BTW I've tried the above codes myself but the performance is still not satisfying 😕 However this is not surprising because it should be as competitive as [this](https://www.kaggle.com/jamesleslie/titanic-neural-network-for-beginners) solution (I haven't submitted to test it, though), which is far more complicated than the above codes 😆

> BTW the best parameters I got is:

```python
best_param = {'optimizer': 'adam', 'optimizer_config': {'lr': 0.07092195938234012}}
```

> So you can try it directly with:

```python
import cflearn
from cfdata.tabular import *

if __name__ == '__main__':
    train = 'titanic_train.csv'
    best_param = {'optimizer': 'adam', 'optimizer_config': {'lr': 0.07092195938234012}}
    _, patterns = cflearn.repeat_with(train, **best_param, read_config={"y": 1}, num_jobs=0)
    ensemble = cflearn.EnsemblePattern(patterns)
```

> And [here](https://www.kaggle.com/c/titanic/discussion/4780) is a discussion on using neural networks for this task, in case you need it 😄

**Comment by impulsecorp** [comment]
I am now deleting the __tmp__ directory each time I run it but it still gives errors both when I run it the example code you gave and also when I run it using the code you gave for the using the optimized settings you already found:

root@server1:~/newautoml# python3 cfl.py
~~~ [warning] delimiter of the given file dataset is not provided, this may cause incorrect parsing
  0%|                                                                                                         | 0/10 [00:00<?, ?it/s]~~~ [warning] '/root/newautoml/__tmp__/ab71a8e1/0/checkpoints' already exists, all of its contents will be removed
  0%|                                                                                                         | 0/10 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "cfl.py", line 10, in <module>
    num_parallel=0
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 368, in tune_with
    hpo.search(x, y, estimators, x_cv, y_cv, **search_config)
  File "/usr/local/lib/python3.6/dist-packages/cftool/ml/hpo/base.py", line 149, in search
    self.patterns[self.last_code] = self._core(param, convert=True, parallel_run=num_jobs > 1)
  File "/usr/local/lib/python3.6/dist-packages/cftool/ml/hpo/base.py", line 91, in _core
    patterns = created if self._converter is None else self._converter(created)
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 326, in _converter
    wrappers = list(map(load_task, next(iter(created[0].values()))))
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 188, in load_task
    return next(iter(load(saving_folder=task.saving_folder).values()))
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 460, in load
    wrappers = {k: Wrapper.load(v, compress=True) for k, v in paths.items()}
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 460, in <dictcomp>
    wrappers = {k: Wrapper.load(v, compress=True) for k, v in paths.items()}
  File "/usr/local/lib/python3.6/dist-packages/cflearn/bases.py", line 836, in load
    pipeline.restore_checkpoint(folder)
  File "/usr/local/lib/python3.6/dist-packages/cflearn/bases.py", line 648, in restore_checkpoint
    self.load_state_dict(torch.load(pipeline_file, map_location=self.model.device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Pipeline:
        size mismatch for model.encoders.10.encoders.embedding.embedding.weight: copying a param with shape torch.Size([148, 8]) from checkpoint, the shape in current model is torch.Size([137, 8]).
        size mismatch for model.encoders.2.encoders.embedding.embedding.weight: copying a param with shape torch.Size([667, 8]) from checkpoint, the shape in current model is torch.Size([615, 8]).
        size mismatch for model.encoders.3.encoders.embedding.embedding.weight: copying a param with shape torch.Size([803, 8]) from checkpoint, the shape in current model is torch.Size([723, 8]).
        size mismatch for model.encoders.8.encoders.embedding.embedding.weight: copying a param with shape torch.Size([681, 8]) from checkpoint, the shape in current model is torch.Size([626, 8]).
root@server1:~/newautoml#


When I run it using your optimized settings:

root@server1:~/newautoml# python3 cfl.py
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:08<00:00,  1.68s/it]
Traceback (most recent call last):
  File "cfl.py", line 7, in <module>
    _, patterns = cflearn.repeat_with(train, **best_param, read_config={"y": 1}, num_jobs=0)
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 237, in repeat_with
    temp_folder=temp_folder, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/cflearn/dist/experiments.py", line 64, in run
    loaded = load_task(task)
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 188, in load_task
    return next(iter(load(saving_folder=task.saving_folder).values()))
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 460, in load
    wrappers = {k: Wrapper.load(v, compress=True) for k, v in paths.items()}
  File "/usr/local/lib/python3.6/dist-packages/cflearn/__init__.py", line 460, in <dictcomp>
    wrappers = {k: Wrapper.load(v, compress=True) for k, v in paths.items()}
  File "/usr/local/lib/python3.6/dist-packages/cflearn/bases.py", line 836, in load
    pipeline.restore_checkpoint(folder)
  File "/usr/local/lib/python3.6/dist-packages/cflearn/bases.py", line 648, in restore_checkpoint
    self.load_state_dict(torch.load(pipeline_file, map_location=self.model.device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Pipeline:
        size mismatch for model.encoders.10.encoders.embedding.embedding.weight: copying a param with shape torch.Size([148, 8]) from checkpoint, the shape in current model is torch.Size([137, 8]).
        size mismatch for model.encoders.2.encoders.embedding.embedding.weight: copying a param with shape torch.Size([667, 8]) from checkpoint, the shape in current model is torch.Size([615, 8]).
        size mismatch for model.encoders.3.encoders.embedding.embedding.weight: copying a param with shape torch.Size([803, 8]) from checkpoint, the shape in current model is torch.Size([723, 8]).
        size mismatch for model.encoders.8.encoders.embedding.embedding.weight: copying a param with shape torch.Size([681, 8]) from checkpoint, the shape in current model is torch.Size([626, 8]).

**Comment by carefree0910** [comment]
In this case I'm afraid that the internal bug in `carefree-data` hurts so much that there's no quick fix for it 😭

I'll fix the bug and release some new versions as soon as possible, terribly sorry for wasting you so much time 😢

**Comment by impulsecorp** [comment]
No problem, I will test it again whenever you want.

**Comment by carefree0910** [comment]
Hi! I've made several changes and now it should be fine. Here's how you could get the latest updates:

```bash
cd /to/the/path/where/you/want/to/store/carefree-learn
pip install -U carefree-toolkit>=0.1.8.1
git clone https://github.com/carefree0910/carefree-learn.git
cd carefree-learn
pip install -e .
```

> BTW In the latest version, I've already included a Titanic example at ./examples/titanic 😉

> And here's one of my submission scores, it is competitive with [this](https://www.kaggle.com/jamesleslie/titanic-neural-network-for-beginners) solution as I've mentioned 😁
![image](https://user-images.githubusercontent.com/15677328/89146087-41d3fd00-d585-11ea-87b5-9bbdcbd32eff.png)

**Comment by impulsecorp** [comment]
I ran it using your demo file and it worked well. It gave me a Kaggle score of 0.78708. Did you do anything differently to get your .81100 score, or was that just due to variance?

**Comment by carefree0910** [comment]
It was just due to variance 😉 In fact, I've commented in the demo file that the score will be ~0.79 😄

**Comment by impulsecorp** [comment]
I tried it now with fcnn and got 0.80622 (I ran it again for fcnn and got 0.79665), but there is big variance with Titanic so hard to tell which is best.  Ensembling tree_dnn with fcnn might give the best results.

**Comment by carefree0910** [comment]
Yes, since Titanic is a small dataset 😁 In fact, [this](https://www.kaggle.com/c/titanic/discussion/4780) discussion shows that 0.80 seems to be the SOTA solution already 🤣

> BTW It is fairly straightforward to ensembe tree_dnn with fcnn in the demo file, simply replace the codes between:

```python
    data_config = {"label_name": "Survived"}
    ...
    predictions = ensemble.predict(test_file).ravel()
```

with

```python
    patterns = []
    for model in ["fcnn", "tree_dnn"]:
        hpo = cflearn.tune_with(
            train_file,
            model=model,
            temp_folder=f"__test_titanic1_{model}__",
            task_type=TaskTypes.CLASSIFICATION,
            data_config=data_config,
            num_parallel=0
        )
        results = cflearn.repeat_with(
            train_file,
            **hpo.best_param,
            models="tree_dnn",
            temp_folder=f"__test_titanic2_{model}__",
            num_repeat=10, num_jobs=0,
            data_config=data_config
        )
        patterns += results.patterns[model]
    ensemble = cflearn.EnsemblePattern(patterns)
```

And it should be fine 😉 I've tried it myself but I only got 0.772 😢 So it might not worth tuning on such a small dataset as Titanic 😫

**Comment by impulsecorp** [comment]
It might do better using a regular ensemble of the two models (averaging the predictions), instead of tuning for it.

**Comment by carefree0910** [comment]
In this case the codes will be much simpler:

```python
    results = cflearn.repeat_with(
        train_file,
        models=["fcnn", "tree_dnn"],
        temp_folder="__test_titanic2__",
        num_repeat=3, num_jobs=0,
        data_config=data_config
    )
    patterns = results.patterns["fcnn"] + results.patterns["tree_dnn"]
    ensemble = cflearn.EnsemblePattern(patterns)
```

I've tried it but only got 0.754 😢

> BTW What I meant to say is that it is hard to tell which method is better based on Titanic's result, since Titanic is too small for Neural Networks 😉

**Comment by impulsecorp** [comment]
Very strange the average score was so much lower than the 2 individual scores. It was worth a try though.
