### ISSUE TITLE
carefree-data and carefree-learn appear to require numpy == 1.20.0

### ISSUE THREAD

**Issue by julianrcook** [carefree0910/carefree-data#2]
When importing either of:

```
from cfdata.tabular import TabularDataset
import cflearn
```

When the following lines in cython_wrappers.py is run with numpy==1.19.2 it will fail

```
try:
    from .cython_utils import *
except ImportError:
    raise

# with error
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

numpy 1.20 is not yet available in anaconda, but if numpy is uninstalled & numpy==1.20.0 is specifically installed via pip, the error disappears.

**Comment by carefree0910** [comment]
Thank you very much for pointing this out! I'll try to fix this compatibility issue ASAP😆

**Comment by carefree0910** [comment]
I've upgraded the dependency of `numpy` & `python` in `README.md`, `setup.py` & `pyproject.toml`, and it should be OK now. If you still encountered this issue from a new, fresh environment under the new instructions, feel free to re-open this issue anytime!
